#!/usr/bin/env bash
# =============================================================================
#  DroidShell — Docs Tools Suite Generator
#
#  Generates:
#    scripts/ds-docs-site.sh          (MkDocs-style static site, Bash-native)
#    scripts/ds-module-graph.sh       (ASCII + Graphviz .dot module graph)
#    scripts/ds-manpages-generate.sh  (manpage-style docs for each ds-* script)
# =============================================================================

set -euo pipefail

ROOT="$HOME/DroidShell"
SCRIPTS="$ROOT/scripts"

mkdir -p "$SCRIPTS"

log(){ echo "[DOCS-TOOLS] $*"; }

# -----------------------------------------------------------------------------
# ds-docs-site.sh — Bash-native static docs site generator
# -----------------------------------------------------------------------------
cat > "$SCRIPTS/ds-docs-site.sh" << 'EOF_SITE'
#!/usr/bin/env bash
# ds-docs-site.sh
# Build a simple static HTML site from docs/*.md into site/
# Very small, Bash-native, no external Markdown parser.

set -euo pipefail

ROOT="$HOME/DroidShell"
DOCS="$ROOT/docs"
SITE="$ROOT/site"

mkdir -p "$SITE"

header_html() {
  cat << 'EOF_H'
<!DOCTYPE html>
<html>
<head>
  <meta charset="utf-8">
  <title>DroidShell Docs</title>
  <style>
    body { font-family: system-ui, sans-serif; max-width: 900px; margin: 2rem auto; padding: 0 1rem; }
    nav a { margin-right: 1rem; }
    pre { background: #111; color: #eee; padding: 0.5rem; overflow-x: auto; }
    code { background: #eee; padding: 0 0.2rem; }
    h1, h2, h3 { border-bottom: 1px solid #ddd; padding-bottom: 0.2rem; }
  </style>
</head>
<body>
<nav>
  <a href="index.html">Home</a>
  <a href="architecture.html">Architecture</a>
  <a href="modules.html">Modules</a>
  <a href="usage.html">Usage</a>
  <a href="troubleshooting.html">Troubleshooting</a>
  <a href="glossary.html">Glossary</a>
</nav>
<hr>
EOF_H
}

footer_html() {
  cat << 'EOF_F'
<hr>
<footer>
  <small>DroidShell Docs - generated by ds-docs-site.sh</small>
</footer>
</body>
</html>
EOF_F
}

md_to_html_body() {
  # Extremely minimal Markdown-to-HTML:
  # - #, ##, ### headings
  # - ``` code fences
  # - blank lines -> <p>
  in_code=0
  while IFS='' read -r line || [ -n "$line" ]; do
    case "$line" in
      '```'*)
        if [ "$in_code" -eq 0 ]; then
          echo "<pre><code>"
          in_code=1
        else
          echo "</code></pre>"
          in_code=0
        fi
        ;;
      \#\#\#\ *)
        text="${line#\#\#\# }"
        echo "<h3>${text}</h3>"
        ;;
      \#\#\ *)
        text="${line#\#\# }"
        echo "<h2>${text}</h2>"
        ;;
      \#\ *)
        text="${line#\# }"
        echo "<h1>${text}</h1>"
        ;;
      '')
        [ "$in_code" -eq 0 ] && echo "<p></p>" || echo
        ;;
      *)
        if [ "$in_code" -eq 1 ]; then
          printf '%s\n' "$(printf '%s' "$line" | sed 's/&/\&amp;/g; s/</\&lt;/g; s/>/\&gt;/g')"
        else
          echo "<p>${line}</p>"
        fi
        ;;
    esac
  done
}

build_page() {
  local src="$1"
  local dst="$2"
  header_html > "$dst"
  md_to_html_body < "$src" >> "$dst"
  footer_html >> "$dst"
  echo "[SITE] Built $(basename "$dst")"
}

main() {
  [ -d "$DOCS" ] || { echo "No docs/ directory"; exit 1; }

  for md in "$DOCS"/*.md; do
    [ -f "$md" ] || continue
    base="$(basename "$md" .md)"
    html="$SITE/$base.html"
    build_page "$md" "$html"
  done

  # Special: map docs/changelog, contributing, legal into site/
  for sub in changelog contributing legal; do
    if [ -d "$DOCS/$sub" ]; then
      mkdir -p "$SITE/$sub"
      for md in "$DOCS/$sub"/*.md "$DOCS/$sub"/LICENSE; do
        [ -f "$md" ] || continue
        name="$(basename "$md")"
        case "$name" in
          *.md)
            base="$(basename "$name" .md)"
            html="$SITE/$sub/$base.html"
            header_html > "$html"
            md_to_html_body < "$md" >> "$html"
            footer_html >> "$html"
            echo "[SITE] Built $sub/$base.html"
            ;;
          LICENSE)
            # Wrap LICENSE in preformatted block
            html="$SITE/$sub/LICENSE.html"
            header_html > "$html"
            echo "<h1>License</h1><pre><code>" >> "$html"
            sed 's/&/\&amp;/g; s/</\&lt;/g; s/>/\&gt;/g' "$md" >> "$html"
            echo "</code></pre>" >> "$html"
            footer_html >> "$html"
            echo "[SITE] Built $sub/LICENSE.html"
            ;;
        esac
      done
    fi
  done
}

main "$@"
EOF_SITE

chmod +x "$SCRIPTS/ds-docs-site.sh"
log "ds-docs-site.sh written."

# -----------------------------------------------------------------------------
# ds-module-graph.sh — ASCII + Graphviz .dot graph
# -----------------------------------------------------------------------------
cat > "$SCRIPTS/ds-module-graph.sh" << 'EOF_GRAPH'
#!/usr/bin/env bash
# ds-module-graph.sh
# Produce a simple module dependency graph:
# - ASCII adjacency list
# - Optional Graphviz .dot file

set -euo pipefail

ROOT="$HOME/DroidShell"
SCRIPTS="$ROOT/scripts"
OUT_DIR="$ROOT/registry/graphs"
mkdir -p "$OUT_DIR"

ASCII_OUT="$OUT_DIR/modules-graph.txt"
DOT_OUT="$OUT_DIR/modules-graph.dot"

# Convention: dependencies are declared in scripts as:
#   # DEPS: ds-foo.sh ds-bar.sh
#
# This script parses those lines.

echo "# DroidShell Module Dependency Graph" > "$ASCII_OUT"

echo "digraph droidshell_modules {" > "$DOT_OUT"
echo "  rankdir=LR;" >> "$DOT_OUT"
echo "  node [shape=box, fontname=\"Helvetica\"];" >> "$DOT_OUT"

for f in "$SCRIPTS"/ds-*.sh; do
  [ -f "$f" ] || continue
  base="$(basename "$f")"
  deps_line="$(grep -E '^# DEPS:' "$f" || true)"
  if [ -z "$deps_line" ]; then
    echo "$base: (no explicit deps)" >> "$ASCII_OUT"
    echo "  \"$base\";" >> "$DOT_OUT"
    continue
  fi
  deps="${deps_line#\# DEPS: }"
  echo "$base: $deps" >> "$ASCII_OUT"
  for d in $deps; do
    echo "  \"$base\" -> \"$d\";" >> "$DOT_OUT"
  done
done

echo "}" >> "$DOT_OUT"

echo "[GRAPH] ASCII: $ASCII_OUT"
echo "[GRAPH] DOT:   $DOT_OUT"
echo "[GRAPH] If you have Graphviz, run: dot -Tpng \"$DOT_OUT\" -o \"$OUT_DIR/modules-graph.png\""
EOF_GRAPH

chmod +x "$SCRIPTS/ds-module-graph.sh"
log "ds-module-graph.sh written."

# -----------------------------------------------------------------------------
# ds-manpages-generate.sh — manpage-style docs for each ds-* script
# -----------------------------------------------------------------------------
cat > "$SCRIPTS/ds-manpages-generate.sh" << 'EOF_MAN'
#!/usr/bin/env bash
# ds-manpages-generate.sh
# Generate manpage-style text files for each ds-* script based on header comments.

set -euo pipefail

ROOT="$HOME/DroidShell"
SCRIPTS="$ROOT/scripts"
MAN_DIR="$ROOT/docs/man"
mkdir -p "$MAN_DIR"

for f in "$SCRIPTS"/ds-*.sh; do
  [ -f "$f" ] || continue
  base="$(basename "$f")"
  name="${base%.sh}"
  out="$MAN_DIR/$name.1.txt"

  {
    echo "$name(1)                    DroidShell Manual                    $name(1)"
    echo
    echo "NAME"
    echo "    $name - DroidShell module"
    echo
    echo "SYNOPSIS"
    echo "    $base [options] ..."
    echo
    echo "DESCRIPTION"
    # Take leading comment block as description
    awk '
      BEGIN { in_header=1 }
      {
        if (in_header == 1) {
          if ($0 ~ /^#!/) next
          if ($0 ~ /^#/) {
            sub(/^# ?/, "", $0)
            print "    " $0
          } else {
            in_header=0
          }
        }
      }
    ' "$f"
    echo
    echo "FILES"
    echo "    $f"
    echo
    echo "SEE ALSO"
    echo "    ds-module-registry.sh, ds-module-docs.sh"
    echo
  } > "$out"

  echo "[MAN] $out"
done
EOF_MAN

chmod +x "$SCRIPTS/ds-manpages-generate.sh"
log "ds-manpages-generate.sh written."

echo "[DOCS-TOOLS] Docs tools suite generation complete."
