#!/usr/bin/env bash
# ds-docs-site.sh
# Build a simple static HTML site from docs/*.md into site/
# Very small, Bash-native, no external Markdown parser.

set -euo pipefail

ROOT="$HOME/DroidShell"
DOCS="$ROOT/docs"
SITE="$ROOT/site"

mkdir -p "$SITE"

header_html() {
  cat << 'EOF_H'
<!DOCTYPE html>
<html>
<head>
  <meta charset="utf-8">
  <title>DroidShell Docs</title>
  <style>
    body { font-family: system-ui, sans-serif; max-width: 900px; margin: 2rem auto; padding: 0 1rem; }
    nav a { margin-right: 1rem; }
    pre { background: #111; color: #eee; padding: 0.5rem; overflow-x: auto; }
    code { background: #eee; padding: 0 0.2rem; }
    h1, h2, h3 { border-bottom: 1px solid #ddd; padding-bottom: 0.2rem; }
  </style>
</head>
<body>
<nav>
  <a href="index.html">Home</a>
  <a href="architecture.html">Architecture</a>
  <a href="modules.html">Modules</a>
  <a href="usage.html">Usage</a>
  <a href="troubleshooting.html">Troubleshooting</a>
  <a href="glossary.html">Glossary</a>
</nav>
<hr>
EOF_H
}

footer_html() {
  cat << 'EOF_F'
<hr>
<footer>
  <small>DroidShell Docs - generated by ds-docs-site.sh</small>
</footer>
</body>
</html>
EOF_F
}

md_to_html_body() {
  # Extremely minimal Markdown-to-HTML:
  # - #, ##, ### headings
  # - ``` code fences
  # - blank lines -> <p>
  in_code=0
  while IFS='' read -r line || [ -n "$line" ]; do
    case "$line" in
      '```'*)
        if [ "$in_code" -eq 0 ]; then
          echo "<pre><code>"
          in_code=1
        else
          echo "</code></pre>"
          in_code=0
        fi
        ;;
      \#\#\#\ *)
        text="${line#\#\#\# }"
        echo "<h3>${text}</h3>"
        ;;
      \#\#\ *)
        text="${line#\#\# }"
        echo "<h2>${text}</h2>"
        ;;
      \#\ *)
        text="${line#\# }"
        echo "<h1>${text}</h1>"
        ;;
      '')
        [ "$in_code" -eq 0 ] && echo "<p></p>" || echo
        ;;
      *)
        if [ "$in_code" -eq 1 ]; then
          printf '%s\n' "$(printf '%s' "$line" | sed 's/&/\&amp;/g; s/</\&lt;/g; s/>/\&gt;/g')"
        else
          echo "<p>${line}</p>"
        fi
        ;;
    esac
  done
}

build_page() {
  local src="$1"
  local dst="$2"
  header_html > "$dst"
  md_to_html_body < "$src" >> "$dst"
  footer_html >> "$dst"
  echo "[SITE] Built $(basename "$dst")"
}

main() {
  [ -d "$DOCS" ] || { echo "No docs/ directory"; exit 1; }

  for md in "$DOCS"/*.md; do
    [ -f "$md" ] || continue
    base="$(basename "$md" .md)"
    html="$SITE/$base.html"
    build_page "$md" "$html"
  done

  # Special: map docs/changelog, contributing, legal into site/
  for sub in changelog contributing legal; do
    if [ -d "$DOCS/$sub" ]; then
      mkdir -p "$SITE/$sub"
      for md in "$DOCS/$sub"/*.md "$DOCS/$sub"/LICENSE; do
        [ -f "$md" ] || continue
        name="$(basename "$md")"
        case "$name" in
          *.md)
            base="$(basename "$name" .md)"
            html="$SITE/$sub/$base.html"
            header_html > "$html"
            md_to_html_body < "$md" >> "$html"
            footer_html >> "$html"
            echo "[SITE] Built $sub/$base.html"
            ;;
          LICENSE)
            # Wrap LICENSE in preformatted block
            html="$SITE/$sub/LICENSE.html"
            header_html > "$html"
            echo "<h1>License</h1><pre><code>" >> "$html"
            sed 's/&/\&amp;/g; s/</\&lt;/g; s/>/\&gt;/g' "$md" >> "$html"
            echo "</code></pre>" >> "$html"
            footer_html >> "$html"
            echo "[SITE] Built $sub/LICENSE.html"
            ;;
        esac
      done
    fi
  done
}

main "$@"
